Update hentaiathome.ts
EhTagTranslation/EhSyringe pull request #1204
Opened 2023-09-07 01:14 UTC by sakuyamaij

Some description of H@H have been updated.

2023-09-07 02:20 UTC, xb2016 requested changes

2023-09-07 02:20 UTC, xb2016 commented on src/services/ui-translation/data/hentaiathome.ts
> +        ' static range(s) assigned: P1 = ': ' 组静态范围：P1 = ',
这里 P1 中的 1 并不是固定值，需要改成正则替换
`[/^ static range\(s\) assigned: P(\d+) = $/, ' 组静态范围：P$1 = '],`

2023-09-07 02:24 UTC, sakuyamaij commented on src/services/ui-translation/data/hentaiathome.ts
> +        ' static range(s) assigned: P1 = ': ' 组静态范围：P1 = ',
还真是。看了下新开的client，冒号后面就直接是P5了

2023-09-07 08:24 UTC, xb2016 approved these changes

2023-09-08 18:14 UTC, merged

2023-09-08 18:14 UTC, OpportunityLiu commented
感谢 @sakuyamaij @xb2016

2023-09-09 02:56 UTC, xb2016 commented
坏消息 被菠萝背刺了 又改东西了。。

2023-09-09 03:18 UTC, sakuyamaij commented
> 坏消息 被菠萝背刺了 又改东西了。。

草